#!perl -w
use strict;
 use Pegex;
 use YAML;

  my  $grammar = <<'...';
# Precedence Climbing grammar:
expr: add-sub
add-sub: mul-div+ % /- ( [ '+-' ])/
mul-div: power+ % /- ([ '*/' ])/
power: token+ % /- '^' /
token: /- '(' -/ expr /- ')'/ | number
number: /- ( '-'? DIGIT* DOT? DIGIT* )/
...

{
    package Calculator;
    use base 'Pegex::Tree';

    sub gotrule {
        my ($self, $list) = @_;
        return $list unless ref $list;

        # Right associative:
        if ($self->rule eq 'power') {
            while (@$list > 1) {
                my ($a, $b) = splice(@$list, -2, 2);
                push @$list, $a ** $b;
            }
        }
        # Left associative:
        else {
            while (@$list > 1) {
                my ($a, $op, $b) = splice(@$list, 0, 3);
                unshift @$list,
                    ($op eq '+') ? ($a + $b) :
                    ($op eq '-') ? ($a - $b) :
                    ($op eq '*') ? ($a * $b) :
                    ($op eq '/') ? ($a / $b) :
					($op eq '^') ? ($a ^ $b) :
                    die;
            }
        }
        return @$list;
    }
}   print "Using the default 'Pegex::Tree' parser\n------------------------------------\n";
    print Dump pegex($grammar)->parse(' 12.56/.5 - ( 3^2 * 4 )');
	print "Using the Custom parser\n------------------------------------------\n";
	 print Dump pegex($grammar, 'Calculator')->parse(' 12.56/.5 - ( 3^2 * 4 )');
	